#!/bin/sh

export NOTIFICATION_GITHUB_TOKEN=${NOTIFICATION_GITHUB_TOKEN}
export SLACK_BOT_OAUTH_TOKEN=${SLACK_BOT_OAUTH_TOKEN}
export SLACK_CHANNEL=${SLACK_CHANNEL}
export SLACK_USER_ID=${SLACK_USER_ID}
export INCLUDE_GITHUB_REPOS=${INCLUDE_GITHUB_REPOS}
export EXCLUDE_GITHUB_REPOS=${EXCLUDE_GITHUB_REPOS}

github-notifications-to-slack
